### ISSUE TITLE
Firebase NodeBB Issue -- warn: Cannot Initialize Firebase App. Please check firebase config!

### ISSUE THREAD

**Issue by vishsid73** [bambusoideae/nodebb-plugin-sso-firebase#1]
Hi,

I am facing some error while using firebase SSO with nodebb. Please refer this stackoverflow for more info: https://stackoverflow.com/questions/47572490/nodebb-firebase-sso

have configured the sso server properly 

 - Added the nodebb url to sso client list json
 - editied the firebase.webclient.json file

On the nodeBB side

 - have installed the firebase sso plugin
 - added the following properties

    

> Firebase Service Account config file:
    http://localhost:3000/firebase.json
> 
> Firebase database url:
    https://nodebbtest1-63699.firebaseio.com
> 
> Firebase Project Id: 
    nodebbtest1-63699
> 
> SSO Server Url: http://localhost:3000/login

When I do not add the Firebase Account Config file, The nodebb log says: 

    30/11 16:07:31 [83900] - info: Initializing NodeBB v1.7.1 http://e22gjd135.ngrok.io
    
    30/11 16:07:31 [83900] - warn: You have no mongo username/password setup!
    
    30/11 16:07:32 [83900] - info: [socket.io] Restricting access to origin: http://e22gjd135.ngrok.io:*
    
    30/11 16:07:32 [83900] - warn: sso-firebase settings is undefined
    
    30/11 16:07:32 [83900] - warn: Please config firebase!
    
    30/11 16:07:32 [83900] - info: Routes added
    
    30/11 16:07:32 [83900] - info: NodeBB Ready
    
    30/11 16:07:32 [83900] - info: Enabling 'trust proxy'
    
    30/11 16:07:32 [83900] - info: NodeBB is now listening on: 0.0.0.0:4567

When I add the config file link, It says:

    30/11 16:43:14 [85763] - info: Initializing NodeBB v1.7.1 http://e22gjd135.ngrok.io
    
    30/11 16:43:14 [85763] - warn: You have no mongo username/password setup!
    
    30/11 16:43:32 [85763] - info: [socket.io] Restricting access to origin: http://e22gjd135.ngrok.io:*
    
    30/11 16:43:36 [85763] - warn: Cannot Initialize Firebase App. Please check firebase config!
    
    30/11 16:43:36 [85763] - info: Routes added
    
    30/11 16:43:36 [85763] - info: NodeBB Ready
    
    30/11 16:43:36 [85763] - info: Enabling 'trust proxy'
    
    30/11 16:43:36 [85763] - info: NodeBB is now listening on: 0.0.0.0:4567

My Firebase Service Account config file looks like:

    { 
        "apiKey": "AIzaSDGFIbJHq3Bot48heAqddfRTQAdHN8zxg",
        "authDomain": "nodebbtest1-63699.firebaseapp.com",
        "databaseURL": "https://nodebbtest1-63699.firebaseio.com",
        "storageBucket": "nodebbtest1-63699.appspot.com"
    }

When I am hitting: 

    http://localhost:3000/login?response_type=token&redirect_uri=http%3A%2F%2Fe22gjd135.ngrok.io%2Fauth%2Ffirebase%2Fcallback

I am getting:

> Internal Error. 

> Oops! Looks like something went wrong!

> /auth/firebase/callback 

> The default Firebase app does not exist. Make
> sure you call initializeApp() before using any of the Firebase
> services.

The NodeBB logs show:

    30/11 16:56:57 [85763] - error: /auth/firebase/callback
     Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
        at FirebaseAppError.Error (native)
        at FirebaseAppError.FirebaseError [as constructor] (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/utils/error.js:39:28)
        at FirebaseAppError.PrefixedFirebaseError [as constructor] (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/utils/error.js:85:28)
        at new FirebaseAppError (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/utils/error.js:119:28)
        at FirebaseNamespaceInternals.app (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/firebase-namespace.js:93:19)
        at FirebaseNamespace.app (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/firebase-namespace.js:322:30)
        at FirebaseNamespace.ensureApp (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/firebase-namespace.js:338:24)
        at FirebaseNamespace.fn (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/firebase-admin/lib/firebase-namespace.js:236:27)
        at loaded (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/nodebb-plugin-sso-firebase/lib/passport-firebase-auth/strategy.js:169:27)
        at NullStore.verify (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/nodebb-plugin-sso-firebase/lib/passport-firebase-auth/state/null.js:11:3)
        at FirebaseStrategy.authenticate (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/nodebb-plugin-sso-firebase/lib/passport-firebase-auth/strategy.js:212:34)
        at attempt (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/passport/lib/middleware/authenticate.js:361:16)
        at authenticate (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/passport/lib/middleware/authenticate.js:362:7)
        at Layer.handle [as handle_request] (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/express/lib/router/layer.js:95:5)
        at next (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/Users/siddharthsrivastava/WebstormProjects/NodeBB/node_modules/express/lib/router/route.js:112:3)

What I am doing Wrong. Please guide.

**Comment by vishsid73** [comment]
Do you know where and what to put in Firebase Service Account config file (admin-> social-> firebase) @bambusoideae

**Comment by bambusoideae** [comment]
You need enter the system path (not URI) to "firebaseServiceAccountConfig" you can download this file from firebase console.
Project Settings -> Service Accounts
For example: /home/user_name/secrets/firebase-admin-service-account.json
You should keep this file private.
